name: eCLM CI Test

# Controls when the action will run.
on: [push, pull_request]

jobs:
  eclm_build_job:
    runs-on: ubuntu-22.04
    env:
      CC: mpicc
      FC: mpifort
      BUILD_DIR: bld
      INSTALL_DIR: install

    steps:
      - uses: actions/checkout@v4
     
      - name: Download eCLM depedencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils pylint wget gfortran openmpi-bin libopenmpi-dev cmake \
                               netcdf-bin libnetcdf-dev libnetcdff-dev libpnetcdf-dev

      - name: Configure eCLM
        run: |
          cmake -S src -B $BUILD_DIR                  \
                -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR   \
                -DCMAKE_C_COMPILER=$CC                \
                -DCMAKE_Fortran_COMPILER=$FC

      - name: Build eCLM
        run: cmake --build $BUILD_DIR

      - name: Install eCLM
        run: cmake --install $BUILD_DIR
